name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download gxc
      run: |
        curl -Lo tools.tar.gz https://github.com/IntelOrca/libsawyer/releases/download/v1.1.0/libsawyer-tools-musl-x64.tar.gz
        tar -C /usr/bin -xf tools.tar.gz
    - name: Create graphics asset pack
      run: node build.mjs --verbose
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: "OpenRCT2 Open Graphics Asset Pack"
        path: out/**/*
